FROM centos/httpd

LABEL maintainer="Jose Carlos Fernandes <joselgn@gmail.com>"

RUN yum -y update && yum -y install wget gcc-c++ make curl vim

WORKDIR /var/www/html

RUN curl -sL https://rpm.nodesource.com/setup_15.x | bash - && \
    yum clean all && yum update -y && \
    yum install -y nodejs --skip-broken && npm install yarn -g

EXPOSE 3000