apiVersion: v1
data:
  APP_ENV: "{{ .Values.backend.app.env }}"
  JWT_ISSUER: "{{ .Values.backend.jwt.issuer }}"
  JWT_AUDIENCE: "{{ .Values.backend.jwt.audience }}"
  JWT_PRIVATE_KEY: "{{ .Values.backend.jwt.private }}"
  JWT_PUBLIC_KEY: "{{ .Values.backend.jwt.public }}"
  JWT_TOKEN_EXP_TIME: "{{ .Values.backend.jwt.token_exp_time }}"
  JWT_REFRESH_TOKEN_EXP_TIME: "{{ .Values.backend.jwt.refresh_token_exp_time }}"
  JWT_TOKEN_TYPE: "{{ .Values.backend.jwt.token_type }}"
  JWT_SCOPES: "{{ .Values.backend.jwt.scopes }}"
  OAUT_CLIENT_ID: "{{ .Values.backend.oaut.client.id }}"
  OAUT_CLIENT_SECRET: "{{ .Values.backend.oaut.client.secret }}"
  OAUT_REDIRECT_URI: "{{ .Values.backend.oaut.redirect.uri }}"
  OAUT_URL_LOGOUT: "{{ .Values.backend.oaut.url.logout }}"
  OAUT_URL_AUTORIZE: "{{ .Values.backend.oaut.url.autorize }}"
  OAUT_URL_ACCESS_TOKEN: "{{ .Values.backend.oaut.url.access }}"
  OAUT_URL_RESOURCE_OWNER_DETAILS: "{{ .Values.backend.oaut.url.resource }}"
  OAUT_SCOPES: "{{ .Values.backend.oaut.scopes }}"
  MAILER_DSN: "{{ .Values.backend.mailer.dsn1 }}"
  MAILER_DSN: "{{ .Values.backend.mailer.dsn2 }}"
  CORS_ALLOW_ORIGIN: "{{ .Values.backend.cors.allow }}"
kind: ConfigMap
metadata:
  name: cm-backend