apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.frontend.name }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: sisbcpf
    app: "{{ .Values.frontend.name }}"
    version: "1"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/instance: sisbcpf
      app: "{{ .Values.frontend.name }}"
      version: "1"
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app.kubernetes.io/instance: sisbcpf
        app: "{{ .Values.frontend.name }}"
        version: "1"
    spec:
      {{- with .Values.frontend.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
          - containerPort: {{ .Values.frontend.ports.port }}
            name: http
        {{- if .Values.healthcheck.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthcheck.readinessProbe.httpGet.path }}
            port: {{ .Values.frontend.ports.port }}
          initialDelaySeconds: {{ .Values.healthcheck.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.healthcheck.readinessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.healthcheck.livenessProbe.enabled }}
        livenessProbe:
          failureThreshold: {{ .Values.healthcheck.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.healthcheck.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.livenessProbe.periodSeconds }}
          tcpSocket:
            port: {{ .Values.frontend.ports.port }}
          timeoutSeconds: {{ .Values.healthcheck.livenessProbe.timeoutSeconds }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
