{{- if .Values.migration.enabled }}
apiVersion: v1
data:
  LIQUIBASE_CHANGELOG: "{{ .Values.migration.file }}"
  LIQUIBASE_DRIVER:	"{{ .Values.migration.driver }}"
  LIQUIBASE_PASSWORD: "{{ .Values.migration.password }}"
  LIQUIBASE_URL: "{{ .Values.migration.url }}"
  LIQUIBASE_USERNAME: "{{ .Values.migration.username }}"
kind: Secret
metadata:
  name: secret-migration
{{- end }}
